### ISSUE TITLE
Shared With Me and/or Team Drive support

### ISSUE THREAD

**Issue by ghost** [plexdrive/plexdrive#130]
In the v3 API all the framework for shared content should be in place..I'd love to have a shared space for curated content among friends.

FWIW rclone has implemented [SharedWithMe](https://github.com/ncw/rclone/blob/56f017c60cbb4b3bea482bcf85145a37295bd0f2/drive/drive.go#L214) support.

**Comment by d0ogie** [comment]
rclone now supports Team Drives in its latest betas! Hopefully some of the code is reusable.

https://github.com/ncw/rclone/issues/885

**Comment by zenjabba** [comment]
yup, and it works pretty good too!

**Comment by TripleFrequency** [comment]
Theoretically, Team Drive support should be pretty simple. If you changed the files.list and files.get calls to include the parameter "supportsTeamDrives=true", then you could theoretically just specify a root-node-id with Plexdrive as the root of a team drive, and it should work.

I am not entirely familiar with the code base, and especially not with Go in general, but I believe this solution should work for team drives, at least.

This document could prove useful in terms of what would require this new query parameter.
https://developers.google.com/drive/v3/web/enable-teamdrives?authuser=1

**Comment by RaymondSchnyder** [comment]
Is there progress on this?

**Comment by dweidenfeld** [comment]
Not right now because I've started to work on a new project and have not time for this right now.

**Comment by dan3805** [comment]
you look busy ! but with this addition plexdrive will become perfect !

**Comment by Rothuith** [comment]
Would be appreciated if you could go on with this fix! It would definitely make PlexDrive complete with features. There would be no reason not to recommend this to anyone.

**Comment by jbd70** [comment]
It looks like @TripleFrequency has worked on adding support [here](https://github.com/TripleFrequency/plexdrive/tree/teamdrive-support). Not sure how much more work is needed.

Are you open to bribes, @dweidenfeld ? :) I'd gladly chip in to a [bountysource](https://www.bountysource.com/issues/45511727-shared-with-me-and-or-team-drive-support) to see this implemented

**Comment by OneHappyForever** [comment]
Yep, would be really great!

**Comment by TripleFrequency** [comment]
@felixbuenemann The larger issue is Team Drives. You can't add a Team Drive to your main Google Drive, as you suggest for shared files/folders.

**Comment by mattbailey** [comment]
Really, this should be two separate issues, team drives and `sharedWithMe` are very different beasts.

**Comment by felixbuenemann** [comment]
@TripleFrequency That's true, that requires your changes that are being integrated in #297.

> Really, this should be two separate issues, team drives and sharedWithMe are very different beasts.

Yepp 😃

**Comment by felixbuenemann** [comment]
Plexdrive 5.1.0 supports Team / Shred Drives, download from: https://github.com/dweidenfeld/plexdrive/releases
