### ISSUE TITLE
Cannot delete Folders / Files

### ISSUE THREAD

**Issue by RaymondSchnyder** [plexdrive/plexdrive#266]
Hey,

I have a bunch of duplicates files and wanted to delete them.

Now the problem is, plexdrive wont delete them as of the log:

WARNING: Could not delete object 0B66aS2JWbHoJOXR6RG45d3hYaGs (oopq969l44q8ok4mcn2a97k5mn91efrjen7o7j9mh8nn0qt7n7mkpu3uk8i73qr62c118k1urj9vkn578aku708d7br93k990d50lnf5gu6ev06spu8534ng9ba5srbr) from API

This is very annoying. How should i delete files correctly?

**Comment by syaifulnizamyahya** [comment]
Probably the same issue as here. https://github.com/dweidenfeld/plexdrive/issues/267

**Comment by RaymondSchnyder** [comment]
No im sorry, unclose this issue. This has NOTHING to do with the issue from @syaifulnizamyahya .
My problem is nothing with Deduplication AT ALL. It has to do that i cannot remove folders which arent empty. Clarification what i meant with duplicate files:

I have the following folders:

/mnt/OldStuff
/mnt/NewStuff

Now i have some folders in OldStuff and NewStuff which are the same, so i wanted to rm -rf the Folders from /mnt/OldStuff. But its not possible, as it fails with EVERY FOLDER, not only one the duplicate ones.

**Comment by syaifulnizamyahya** [comment]
Maybe user rights? What is your mount options?

**Comment by RaymondSchnyder** [comment]
I mount everything with the user 1000 and group 1000, everything is read and writeable.

**Comment by RaymondSchnyder** [comment]
@dweidenfeld Would you kindly reopen the issue? Thanks.

**Comment by syaifulnizamyahya** [comment]
What do you mean writeable? You cant write on plexdrive mount. See readme.

**Comment by RaymondSchnyder** [comment]
@syaifulnizamyahya
Off course i cant write, but i can delete.
And the deletion of folders doesnt work at all for me, i have to clean them before i delete the folder, and even this doesnt work at all times. And you can imagine how nice it is to have the folder locally deleted but remote he is still there and undeleteable.

**Comment by RaymondSchnyder** [comment]
@syaifulnizamyahya
And what i meant with writeable was that i can access the files and change the name for example.

**Comment by RaymondSchnyder** [comment]
Just to clarify, the workaround (which works like 60% of the time), is to delete all content in the folder first, wait a bit, and then deleting the folder.

**Comment by RaymondSchnyder** [comment]
This issue is over 2 years old and it never appeared again so i should close this.
