### ISSUE TITLE
Plexdrive 5 using excessive data

### ISSUE THREAD

**Issue by Qwatuz** [plexdrive/plexdrive#301]
Been having an issue with Plexdrive 5 downloading more than it should be. For example when scanning in new items it will max out my 1gbps - Even when using 10M chunks.

This leads to interesting vnstats:

```                      rx      /      tx      /     total    /   estimated
 enp1s0f0:
       May '18     56.72 TiB  /    8.78 TiB  /   65.49 TiB
       Jun '18     39.02 TiB  /   19.28 TiB  /   58.30 TiB  /   61.00 TiB
     yesterday    887.94 GiB  /  237.34 GiB  /    1.10 TiB
         today    528.83 GiB  /  147.26 GiB  /  676.08 GiB  /    0.98 TiB


                      rx      /      tx      /     total    /   estimated
 eno1:
       May '18     46.75 TiB  /   10.10 TiB  /   56.86 TiB
       Jun '18     35.39 TiB  /   10.10 TiB  /   45.49 TiB  /   48.08 TiB
     yesterday    616.75 GiB  /  129.14 GiB  /  745.89 GiB
         today     64.87 GiB  /   11.25 GiB  /   76.12 GiB  /  198.21 GiB
```

I never had this issue on previous Plexdrive versions or when using rclone cache.

I have heard of others having this problem although it's not overly common it seems.

We have tried disabling anything that could accidentally download whole files, e.g Subzero, plex_autoscan etc.

Mount command

```
/usr/local/bin/plexdrive mount -v 3 --refresh-interval=1m --chunk-check-threads=8 --chunk-load-threads=16 --chunk-load-ahead=8 --chunk-size=10M --max-chunks=250 --fuse-options=allow_other,read_only -c /home/user/data/.Automation/.plexdrive --cache-file=/home/user/data/.Automation/.plexdrive/cache.bolt /home/user/plexdrive5
```

**Comment by damianharouff** [comment]
This project seems more or less abandoned.

Anyway, I too was having massive amounts of data used until I set "Generate chapter thumbnails" in Settings -> Library to "never". Make sure to click the "Show Advanced" button to see these options. 
![image](https://user-images.githubusercontent.com/2953243/42896094-ba4a7960-8a70-11e8-93fe-ff3fc0249a6d.png)

Plex seems to scan the entire file (which means downloading the entire file) to find chapters, so turning this off stops Plex from downloading the entire thing. Data usage is far more acceptable now; this is on a ~27 TB library mid-month that's still filling:
```
   monthly
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
       Jun '18      1.86 TiB |   18.17 GiB |    1.88 TiB |    6.37 Mbit/s
       Jul '18      7.85 TiB |  117.04 GiB |    7.96 TiB |   45.70 Mbit/s
     ------------------------+-------------+-------------+---------------
     estimated     13.71 TiB |  204.46 GiB |   13.91 TiB |
```

**Comment by Qwatuz** [comment]
Thanks for the post @damianharouff but i've already disabled those options and even went a day without adding new content or scanning Plex.

**Comment by Qwatuz** [comment]
Yes it's Plexdrive v5. I have downgraded to v4 and the problem is no longer.

**Comment by bayoumedic** [comment]
exact same problem here.

**Comment by bayoumedic** [comment]
where can i find version 4

**Comment by Qwatuz** [comment]
@bayoumedic https://i.imgur.com/LkQd7sc.png

**Comment by felixbuenemann** [comment]
If you use `--chunk-load-ahead=8`, just accessing 1 byte of a file will cause 9 chunks or 90 MiB to be loaded. If you are scanning a large library for the first time set `--chunk-load-ahead=0`.

Even for normal use `--chunk-load-ahead=8` seems excessive. If your server has good peering to google a load ahead of 1 to 3 should suffice even for high bitrate 4k.
