### ISSUE TITLE
Plexdrive doesn't work as a service. 

### ISSUE THREAD

**Issue by varoOP** [plexdrive/plexdrive#323]
I have the following service enabled : 
```
# /etc/systemd/system/plexdrive.service

[Unit]
Description=Plexdrive
AssertPathIsDirectory=/home/varo/plexdrive
After=network-online.target

[Service]
Type=simple
User=varo
Group=varo 
ExecStart=/bin/plexdrive mount -v 3 --chunk-check-threads=16 --chunk-load-threads=16 --chunk-load-ahead=16 --max-chunks=256 -o allow_other /home/varo/plexdrive -c /home/varo/.plexdrive
ExecStop=/bin/fusermount -uz /home/varo/plexdrive
Restart=on-abort

[Install]
WantedBy=default.target
```

I get the following error when I reboot my arch linux system : 
```
● plexdrive.service - Plexdrive
   Loaded: loaded (/etc/systemd/system/plexdrive.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-05-19 08:37:51 IST; 1min 10s ago
  Process: 548 ExecStart=/bin/plexdrive mount -v 3 --chunk-check-threads=16 --chunk-load-threads=16 --chunk-load-ahead=16 --max-chunks=256 -o allow_other /home/varo/plexdrive -c /home/varo/.plexdrive (code=exited, status=5)
 Main PID: 548 (code=exited, status=5)

May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] DEBUG  : Getting start page token from cache
May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] DEBUG  : Last change id found, continuing getting changes (64211)
May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] INFO   : First cache build process started...
May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] DEBUG  : Getting root from API
May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] DEBUG  : Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id%2C+name%2C+mimeType%2C+modifiedTime%2C+size%2C+explicitlyTrashed%2C+parents%2C+capabilities%2FcanTrash: Post https://accounts.google.com/o/oauth2/token: dial tcp>
May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] WARNING: Could not get object root from API
May 19 08:37:51 Vladilena plexdrive[548]: [BIN/PLEXDRIVE] [2019-05-19 08:37] DEBUG  : cannot obtain root node: Could not get root object
May 19 08:37:51 Vladilena plexdrive[548]: 
May 19 08:37:51 Vladilena systemd[1]: plexdrive.service: Main process exited, code=exited, status=5/NOTINSTALLED
May 19 08:37:51 Vladilena systemd[1]: plexdrive.service: Failed with result 'exit-code'.
~
```

It works fine if the service is disabled and the service is started normally after a reboot. 
If the service is enabled and I first unmount with fusermount -uz /home/varo/plexdrive and then restart the service it still works. 
So, it works if the service is disabled and then started after a reboot.
It also works if the service is enabled, I unmount the plexdrive folder and restart it. 
It doesn't work if the service is enabled and then i reboot. 
The status is this when it's working fine :  

```
● plexdrive.service - Plexdrive
   Loaded: loaded (/etc/systemd/system/plexdrive.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-05-19 08:09:36 IST; 5s ago
 Main PID: 2525 (plexdrive)
    Tasks: 14 (limit: 4915)
   Memory: 15.5M
   CGroup: /system.slice/plexdrive.service
           └─2525 /bin/plexdrive mount -v 3 --chunk-check-threads=16 --chunk-load-threads=16 --chunk-load-ahead=16 --max-chunks=256 -o allow_other /home/varo/plexdrive -c /home/varo/.plexdrive

May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] DEBUG  : Loading token from cache
May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] DEBUG  : Checking for changes
May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] DEBUG  : Getting start page token from cache
May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] INFO   : Mounting path /home/varo/plexdrive
May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] DEBUG  : Last change id found, continuing getting changes (64423)
May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] INFO   : First cache build process started...
May 19 08:09:36 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] DEBUG  : Getting root from API
May 19 08:09:39 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] INFO   : Processed 137 items / deleted 14 items / updated 123 items
May 19 08:09:39 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] DEBUG  : Storing page token 65252 in cache
May 19 08:09:39 Vladilena plexdrive[2525]: [BIN/PLEXDRIVE] [2019-05-19 08:09] INFO   : First cache build process finished!
~
```

**Comment by felixbuenemann** [comment]
Looks like plexdrive is starting up before the network is reachable, which should be ensured by `After=network-online.target`.

What's the output of `systemctl status network-online.target` and `systemctl status network.target`?

I remember another user with a similar problem that was missing the `network-online.target` and had to depend on `network.target` instead.

The example systemd unit works fine on Ubuntu, but might need tweaking for other Linux distributions.

**Comment by TheGlenn88** [comment]
I've had the same issue for a long time, changing network-online.target to network.target solved it

**Comment by philarticolo31** [comment]
Hi, i Have this problem with plexdrive.service... the service will not start on boot.
If i launch the command manually i don't have problems... anyone can help me?


`pi@raspberrypi:~ $ sudo systemctl status plexdrive
● plexdrive.service - Plexdrive
   Loaded: loaded (/etc/systemd/system/plexdrive.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-12-10 20:28:20 CET; 1min 44s ago
  Process: 444 ExecStart=/usr/bin/plexdrive -o allow_other ~/drive/ (code=exited, status=3)
 Main PID: 444 (code=exited, status=3)

dic 10 20:28:20 raspberrypi plexdrive[444]: 1. Please go to https://console.developers.google.com/
dic 10 20:28:20 raspberrypi plexdrive[444]: 2. Create a new project
dic 10 20:28:20 raspberrypi plexdrive[444]: 3. Go to library and activate the Google Drive API
dic 10 20:28:20 raspberrypi plexdrive[444]: 4. Go to credentials and create an OAuth client ID
dic 10 20:28:20 raspberrypi plexdrive[444]: 5. Set the application type to 'other'
dic 10 20:28:20 raspberrypi plexdrive[444]: 6. Specify some name and click create
dic 10 20:28:20 raspberrypi plexdrive[444]: 7. Enter your generated client ID: [USR/BIN/PLEXDRIVE] [2019-12-10 20:28] ERROR  :
dic 10 20:28:20 raspberrypi plexdrive[444]: 
dic 10 20:28:20 raspberrypi systemd[1]: plexdrive.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
dic 10 20:28:20 raspberrypi systemd[1]: plexdrive.service: Failed with result 'exit-code'.
lines 1-16/16 (END)
`

**Comment by felixbuenemann** [comment]
If the systemd unit is running as root and your usually running plexdrive as user “pi” that won’t work. 

Update the unit to run as user pi and replace ~/drive with the absolute path like /home/pi/drive.

**Comment by philarticolo31** [comment]
> If the systemd unit is running as root and your usually running plexdrive as user “pi” that won’t work.
> 
> Update the unit to run as user pi and replace ~/drive with the absolute path like /home/pi/drive.

Ok, thankyou. 
I'm a newbie on linux, so how can I update de Unit to run as user pi?
Just adding User=pi under the [Unit] string in the .service file?

Thank you

**Comment by felixbuenemann** [comment]
Yes, adding `User=pi` is correct.

What errors are you getting?

**Comment by felixbuenemann** [comment]
You also need to add the line `user_allow_other` to `/etc/fuse.conf`.

**Comment by philarticolo31** [comment]
Hi @felixbuenemann , thanks for your reply.
I've just added  the line `user_allow_other` to `/etc/fuse.conf`when I installed plexdrive.

With the .service file configured and posted before, I get this error:
```
pi@raspberrypi:~ $ sudo systemctl status plexdrive
● plexdrive.service - Plexdrive
   Loaded: loaded (/etc/systemd/system/plexdrive.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-12-12 12:25:56 CET; 1min 35s ago
  Process: 461 ExecStart=/usr/bin/plexdrive -o allow_other /home/pi/drive/ (code=exited, status=5)
 Main PID: 461 (code=exited, status=5)

dic 12 12:25:52 raspberrypi systemd[1]: Started Plexdrive.
dic 12 12:25:56 raspberrypi systemd[1]: plexdrive.service: Main process exited, code=exited, status=5/NOTINSTALLED
dic 12 12:25:56 raspberrypi systemd[1]: plexdrive.service: Failed with result 'exit-code'.
```
In the File Manager I see the drive mounted, but when i try to open to see if I can view the files that are inside I get an error that says that the directory `/home/pi/drive` is invalid. 

If i run in the terminal the command: 
`pi@raspberrypi:~ $ plexdrive -v 3 -o allow_other ~/drive` everything works correctly. 

One more time, thanks

**Comment by philarticolo31** [comment]
> You also need to add the line `user_allow_other` to `/etc/fuse.conf`.

This is  my file:
```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

**Comment by felixbuenemann** [comment]
@philarticolo31 Can this issue be closed?

**Comment by philarticolo31** [comment]
Yes please
Il 3 apr 2020, 13:45 +0200, Felix Bünemann <notifications@github.com>, ha scritto:
