### ISSUE TITLE
Teamdrive root id is not working

### ISSUE THREAD

**Issue by Nottt** [plexdrive/plexdrive#333]
Teamdrive root id doesn't seem to work anymore....

Running this

```
/opt/plexdrive/plexdrive mount -v 3 --refresh-interval=1m --chunk-check-threads=8 --chunk-load-threads=8 --chunk-load-ahead=0 --chunk-size=10M --max-chunks=800 --root-node-id=0AArHY_zU--mnUk9PVA --fuse-options=allow_other,read_only --config=/opt/plexdrive --cache-file=/opt/plexdrive/cache.bolt /mnt/plexdrive
```

Just results in:

```
[OPT/PLEXDRIVE/PLEXDRIVE] [2019-09-06 05:22] DEBUG  : googleapi: Error 404: File not found: 0ABgSTsqzp7W6Uk9PVA., notFound
[OPT/PLEXDRIVE/PLEXDRIVE] [2019-09-06 05:22] WARNING: Could not get object 0ABgSTsqzp7W6Uk9PVA from API
```

I tried `5.0.0-beta.1501610675` and `5.0.0`

**Comment by EchterAgo** [comment]
I see you tried with the binary. There is no released / binary version that has team drive support. You will need to compile this yourself. If you're using Arch Linux, I published an AUR package here: https://aur.archlinux.org/packages/plexdrive-git

**Comment by Dunkstormen** [comment]
I'm running into similar issues using the latest stable release on Debian 10.
Any advice on what I should do differently to get teamdrives to work? Perhaps some sort of step by step?

**Comment by Nottt** [comment]
Steps to compile it:

```
1. install go
2. mkdir $GOPATH/src
3. cd $GOPATH/src
4. go get github.com/dweidenfeld/plexdrive
5. cd $GOPATH/src/github.com
6. git clone https://github.com/dweidenfeld/plexdrive.git
7. cd $GOPATH/src/github.com/plexdrive
8. go build -o /tmp/plexdrive
9. use the new file /tmp/plexdrive
```

I'll leave this open so it can help others too! 

The only thing I noticed, that i never saw in the releases was this warning messages:

```
[OPT/PLEXDRIVE/PLEXDRIVE] [2019-09-10 04:52] WARNING: Skipping nil file
```

Can't speak for it's stability as of now, but teamdrives works now

**Comment by felixbuenemann** [comment]
go get -u github.com/dweidenfeld/plexdrive

should be all that’s needed to install to $GOPATH/bin, the other steps are not needed.

**Comment by felixbuenemann** [comment]
You need to upgrade to Plexdrive 5.1.0 or later: https://github.com/dweidenfeld/plexdrive/releases
