### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by ChrisColotti** [plexdrive/plexdrive#337]
Is this still being developed?  It's still working well, but as Google changes come often I am worried it will stop working one day.  It's been solid so far but curious.

**Comment by felixbuenemann** [comment]
Well it is open source software, so you can always fork it and do your own fixes if it goes stale.

That said even though dweidenfeld is no longer actively working on the project, there are several contributors that can handle PRs and fixes, so I wouldn't be too worried.

**Comment by felixbuenemann** [comment]
I have stepped up as the official maitainer, so yeah, it is still being developed and I've got quite a lot of fixes and features in the pipeline.
