### ISSUE TITLE
Still unable to download from plexdrive mount on 1cpu

### ISSUE THREAD

**Issue by bin28281010** [plexdrive/plexdrive#338]
The latest version still has the problem that can't pull date from plexdrive mount, when the vps is 1cpu.

when I use the vps with 1 cpu, I can see my files and browse the mount but cant download anything.
But when i use the other vps with 2cpu it works.
So is anyone here can solve it?

**Comment by felixbuenemann** [comment]
Did you build the latest version from the master branch?

**Comment by bin28281010** [comment]
> Did you build the latest version from the master branch?

nope, let me try.

**Comment by bin28281010** [comment]
It works fine. So why not update the latest version in case others meet the same problem.

**Comment by bin28281010** [comment]
no, I found one edition on a post, and it works.
here is the post:
https://github.com/dweidenfeld/plexdrive/issues/249


Felix Bünemann <notifications@github.com>于2020年1月20日 周一19:51写道：

**Comment by felixbuenemann** [comment]
You need to upgrade to Plexdrive 5.1.0 or later: https://github.com/dweidenfeld/plexdrive/releases
