### ISSUE TITLE
--drive-id is not in the command list

### ISSUE THREAD

**Issue by Kanekid2m** [plexdrive/plexdrive#347]
Hi,

I downloaded today plexdrive 5.0.0 on my linux system and when I try to add team drive I look for the --drive-id command but I cant find it. Later after I read here I saw  felixbuenemann updating the code and it should now work. I tried to compile it but I am really don't know how to compile so I hope maybe you can give me a compiled version of it or publish it here because I need it however to be public to be able to download it. 

Best regadrs

**Comment by kiityman1** [comment]
Same issue

**Comment by felixbuenemann** [comment]
You need to upgrade to Plexdrive 5.1.0 or later: https://github.com/dweidenfeld/plexdrive/releases
