### ISSUE TITLE
Problem: Not all file show...

### ISSUE THREAD

**Issue by gandalf764** [plexdrive/plexdrive#352]
I have 1 directory with 1309 file in googledrive, same directory in plexdrive show only 576 file...
I have stopped and restart plexdrive and server, but same problem.
If i go in googledrive and rename  1 file not show in plexdrive, this file after 1 minite show regular in plexdrive.
Same thing if i move this file in another folder and remove again in original folder (always in googledrive) plexdrive show this file correcrly.
Why this? I hope in a solution or i must move all missed file and remove again for show in plexdrive .
Sorry for bad english.
Thanx

**Comment by fuomag9** [comment]
Same issue happens to me, rebuilding cache seem to fix it but it's not a very easy to use solution

**Comment by Nothing4You** [comment]
i'm not sure i understand your issue correctly.
a part of it seems to be that you're wondering about the delay for changes to show up in plexdrive?
that is because plexdrive only checks for changes once a minute by default (can be changed with `--refresh-interval duration`)

**Comment by felixbuenemann** [comment]
Have you tried compoling from master yet? There have been some bugfixes for change tracking.

**Comment by felixbuenemann** [comment]
Btw. we should probably add a commandline option or something similar to force a full resync of the change database.

**Comment by gandalf764** [comment]
Is not a provlem of delay... If i wait 1 hours or 1 day nothing change...
The only way to show a file in this folder is make a change from web google
drive, for any file.
I hope you understand, if not i can add screenshot

Il sab 7 mar 2020, 00:06 Felix Bünemann <notifications@github.com> ha
scritto:

**Comment by felixbuenemann** [comment]
Pleas upgrade to Plexdrive 5.1.0 (https://github.com/plexdrive/plexdrive/releases/tag/5.1.0), remove `~/.plexdrive/cache.bolt` and restart Plexdrive.

If the problem persists let me know.

**Comment by gandalf764** [comment]
i have upgraded plexdrive ti 5.1.0 but same problem...
here an example:
![image](https://user-images.githubusercontent.com/41706025/77428634-afeb0500-6dd8-11ea-92b2-17f9e1d88772.png)

**Comment by felixbuenemann** [comment]
Did you remove the cache.bolt and restarted plexdrive after the upgrade?

**Comment by gandalf764** [comment]
yes sure..
I noticed that it only happens when I move a folder with some files inside.
If I move (always from gdrive) only the files, the problem does not occur.

**Comment by gandalf764** [comment]
after a while it seems to be working properly. I don't know if it's a coincidence. we await the opinion of others.

**Comment by gandalf764** [comment]
after some time i am testing the new version, i can say that the problem is solved.
maybe initially I was wrong, maybe I hadn't deleted the cache.bolt file
Now all the files appear correctly. Thanks a lot you're a genius!
