### ISSUE TITLE
i need help to create my plexdrive.service

### ISSUE THREAD

**Issue by gandalf764** [plexdrive/plexdrive#356]
have create this:

> [Unit]
> Description=Plexdrive
> After=network-online.target
> 
> [Service]
> User=gandalf76
> Type=simple
> ExecStart=/home/gandalf76/apps/plexdrive mount -c ~/.plexdrive -o allow_other -v 4 --chunk-load-ahead=0 --refresh-interval=1m ~/mnt/plexdrive/
> ExecStop=/bin/fusermount -uz ~/mnt/plexdrive
> Restart=on-abort
> 
> [Install]
> WantedBy=default.target

but the result is:

> ● plexdrive.service - Plexdrive
>    Loaded: loaded (/etc/systemd/system/plexdrive.service; disabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2020-03-31 16:28:30 CEST; 4s ago
>   Process: 1100 ExecStart=/home/gandalf76/apps/plexdrive mount -c ~/.plexdrive -o allow_other -v 4 --chunk-load-ahead=0 --refresh-interval=1m ~/mnt/plexdrive/ (code=exited, status=1/FAILURE)
>  Main PID: 1100 (code=exited, status=1/FAILURE)
> 
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] DEBUG  : refresh-interval     : 1m0s
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] DEBUG  : fuse-options         : allow_other
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] DEBUG  : UID                  : 1000
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] DEBUG  : GID                  : 1000
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] DEBUG  : umask                : ----------
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] ERROR  : Could not create configuration directory
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 16:28] DEBUG  : mkdir ~: permission denied
> Mar 31 16:28:30 vmi360743.contaboserver.net plexdrive[1100]:
> Mar 31 16:28:30 vmi360743.contaboserver.net systemd[1]: plexdrive.service: Main process exited, code=exited, status=1/FAILURE
> Mar 31 16:28:30 vmi360743.contaboserver.net systemd[1]: plexdrive.service: Failed with result 'exit-code'.
> 

what am I wrong or forget?
I state that I use ubuntu 18.04
plexdrive is located in the dir ~ / apps / plexdrive
and when I use this command to start it, it works correctly:

> /sbin/start-stop-daemon -S -u $USER -d $HOME --exec /usr/bin/screen -- -dmS  plexdrive ~/apps/plexdrive mount -c ~/.plexdrive -o allow_other -v 4 --chunk-load-ahead=0 --refresh-interval=1m ~/mnt/plexdrive

**Comment by felixbuenemann** [comment]
You cannot use `~` in systemd unit, since your command is not run in a shell and I think not even the HOME environment variable is set by default, just hardcode the full mount path. Also `--chunk-load-ahead=0` will give absolutely terrible performance, use at least 1.

**Comment by gandalf764** [comment]
now i have this:

> [Unit]
> Description=Plexdrive
> After=network-online.target
> 
> [Service]
> User=gandalf76
> Type=simple
> ExecStart=/home/gandalf76/apps/plexdrive mount -c ~/.plexdrive -o allow_other -v 4 --chunk-load-ahead=1 --refresh-interval=1m /home/gandalf76/mnt/pl$
> ExecStop=/bin/fusermount -uz home/gandalf76/mnt/plexdrive
> Restart=on-abort
> 
> [Install]
> WantedBy=default.target

but same result:

> ● plexdrive.service - Plexdrive
>    Loaded: loaded (/etc/systemd/system/plexdrive.service; disabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2020-03-31 20:49:51 CEST; 2min 41s ago
>   Process: 32693 ExecStart=/home/gandalf76/apps/plexdrive mount -c ~/.plexdrive -o allow_other -v 4 --chunk-load-ahead=1 --refresh-interval=1m /home/
>  Main PID: 32693 (code=exited, status=1/FAILURE)
> 
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] DEBUG  : refresh-interval     : 1m0s
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] DEBUG  : fuse-options         : allo
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] DEBUG  : UID                  : 1000
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] DEBUG  : GID                  : 1000
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] DEBUG  : umask                : ----
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] ERROR  : Could not create configurat
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]: [HOME/GANDALF76/APPS/PLEXDRIVE] [2020-03-31 20:49] DEBUG  : mkdir ~: permission denied
> Mar 31 20:49:51 vmi360743.contaboserver.net systemd[1]: plexdrive.service: Main process exited, code=exited, status=1/FAILURE
> Mar 31 20:49:51 vmi360743.contaboserver.net plexdrive[32693]:
> Mar 31 20:49:51 vmi360743.contaboserver.net systemd[1]: plexdrive.service: Failed with result 'exit-code'.

how i can solve? thanx

**Comment by bluenazgul** [comment]
running into a simlar issue:
`./sbin/plexdrive mount -c ~/.plexdrive -o allow_other -v 4 --refresh-interval=1m ./mnt/plexdrive`  is working perfect

```
[Unit]
Description=Plexdrive
AssertPathIsDirectory=/mnt/plexdrive
After=network-online.target

[Service]
Type=notify
ExecStart=/sbin/plexdrive mount -c /.plexdrive -o allow_other -v 2 --refresh-interval=1m /mnt/plexdrive
ExecStopPost=-/bin/fusermount -quz /mnt/plexdrive
Restart=on-abort

[Install]
WantedBy=default.target
```

but the service dont work

> root@Plex:/sbin# journalctl -xe
> -- 
> -- A start job for unit plexdrive.service has begun execution.
> -- A start job for unit plexdrive.service has begun execution.
> -- A start job for unit plexdrive.service has begun execution.
> -- A start job for unit plexdrive.service has begun execution.
> -- A start job for unit plexdrive.service has begun execution.
> -- 
> -- The job identifier is 265.
> Aug 08 17:58:27 Plex plexdrive[957]: 1. Please go to https://console.developers.google.com/
> Aug 08 17:58:27 Plex plexdrive[957]: 2. Create a new project
> Aug 08 17:58:27 Plex plexdrive[957]: 3. Go to library and activate the Google Drive API
> Aug 08 17:58:27 Plex plexdrive[957]: 4. Go to credentials and create an OAuth client ID
> Aug 08 17:58:27 Plex plexdrive[957]: 5. Set the application type to 'other'
> Aug 08 17:58:27 Plex plexdrive[957]: 6. Specify some name and click create
> Aug 08 17:58:27 Plex plexdrive[957]: 7. Enter your generated client ID: [SBIN/PLEXDRIVE] [2021-08-08 17:58] ERROR  : Could not read con
> Aug 08 17:58:27 Plex plexdrive[957]: 
> Aug 08 17:58:27 Plex systemd[1]: plexdrive.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
> -- Subject: Unit process exited
> -- Defined-By: systemd
> -- Support: https://www.debian.org/support
> -- 
> -- An ExecStart= process belonging to unit plexdrive.service has exited.
> -- 
> -- The process' exit code is 'exited' and its exit status is 3.
> Aug 08 17:58:27 Plex systemd[1]: plexdrive.service: Failed with result 'exit-code'.
> -- Subject: Unit failed
> -- Defined-By: systemd
> -- Support: https://www.debian.org/support
