### ISSUE TITLE
[Feature Request] Support for Google shortcuts

### ISSUE THREAD

**Issue by edrock200** [plexdrive/plexdrive#358]
Hopefully this is the right place for this sort of thing, apologies if not. 

Google has rolled out a new beta feature called shortcuts in which a shortcut can be created from any folder to any team drive or my drive location. It appears plexdrive can see this shortcuts but doesn't see them as directories. Upon further research I saw in the rclone forum it's not part of the Google sdk yet, but once it's added would be a nice feature to plexdrive. Just mount one drive will all your shortcuts vs multiple mounts/mergerfs. 

More info here:
https://gsuiteupdates.googleblog.com/2019/08/drive-shortcuts-beta.html?m=1

Here's the rclone feature request as well for context:
https://github.com/rclone/rclone/issues/4098

**Comment by loctruong96** [comment]
This would be an amazing additional feature.

**Comment by felixbuenemann** [comment]
It looks like the go drive sdk doesn't support them yet and the beta program is closed, so until this changes there isn't much we can do.

**Comment by edrock200** [comment]
Yes that's what I was trying to say in my original post but autocorrect got the best of me. :) I've edited my op to correctly reflect this. Just wanted to post this so it's on the radar.  Thanks in advance if/when this can be done!

**Comment by edrock200** [comment]
Fingers crossed that the sdk add is coming soon!
https://issuetracker.google.com/issues/152865050

**Comment by darthShadow** [comment]
Just FYI, the support for shortcuts has been added to the drive API.

**Comment by edrock200** [comment]
Just saw! Looks like rclone has a beta implemented. Link for reference: https://github.com/rclone/rclone/issues/4098

**Comment by phanirithvij2000** [comment]
@felixbuenemann can you review #397?

**Comment by felixbuenemann** [comment]
> @felixbuenemann can you review #397?

I started a review.

**Comment by felixbuenemann** [comment]
Support for shortcuts is now in master. It would be great to get some feedback here, if it works well for you, before I make a new release.
