### ISSUE TITLE
Clear Client ID

### ISSUE THREAD

**Issue by staticgroup** [plexdrive/plexdrive#368]
Hey team,

I accidently entered wrong client id , and I've tried removing plexdrive and even manually removing the files from .qpkg (this is the qnap variet) but it still just gives me the google link for verification and wont let me reenter the client id etc. any idea how to clear?

**Comment by felixbuenemann** [comment]
You can remove the $HOME/.plexdrive folder and restart configuration.

**Comment by staticgroup** [comment]
thank you
