### ISSUE TITLE
Which version to use in Odroid C2

### ISSUE THREAD

**Issue by dinjojo** [plexdrive/plexdrive#396]
I tried some of them none worked 

# uname -a
Linux odroid 3.16.85-65 #1 SMP PREEMPT Mon Jan 18 13:32:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Nothing4You** [comment]
hint: try asking your favorite search engine about "aarch64" and you should find an alternative name that matches one of the available release artifacts

**Comment by dinjojo** [comment]
I tried with arm64 and it throwed me this error

root@odroid:~# ./plexdrive-linux-arm64
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 20:23] ERROR  : Command  not found
root@odroid:~#

**Comment by Nothing4You** [comment]
You always need to use `mount` as first parameter, as far as I can see this is only documented in the example given [here](https://github.com/plexdrive/plexdrive#installation) which is a bit unfortunate, especially as it doesn't show up in `--help`.

**Comment by dinjojo** [comment]
Thank you for help was able to mount but i see these coming and I don't really want to download anything but just add to plex.

4] [2021-03-05 22:04] DEBUG  : Starting download 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:0 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:0
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:4592762880 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:10485760
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:4676648960
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:20971520 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:10485760 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:4267704320
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:31457280 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:20971520
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:0 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:31457280
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:10485760 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:0
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:20971520
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:20971520 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:31457280 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:31457280
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:0 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:10485760
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:10485760 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1qmLDlpiieLioEtonYe0ij0NuF6D1LsHY:4592762880
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:0 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:10485760
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:77793853440 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:20971520
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:4676648960 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:0
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:20971520 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:31457280
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:31457280 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:10485760
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:0
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:4267704320 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:20971520
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1tH0jy2yRSH9CgOuKtsI65eWnD_iNWFd9:0 (preload: false)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1tH0jy2yRSH9CgOuKtsI65eWnD_iNWFd9:10485760 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:4676648960
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1tH0jy2yRSH9CgOuKtsI65eWnD_iNWFd9:31457280 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:77793853440
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1O8MoBh0hgM08EbAW285vaLkcX3P4n5h4:31457280
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1tH0jy2yRSH9CgOuKtsI65eWnD_iNWFd9:20971520 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1tH0jy2yRSH9CgOuKtsI65eWnD_iNWFd9:0
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:10485760 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Deleted chunk 1tH0jy2yRSH9CgOuKtsI65eWnD_iNWFd9:10485760
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:04] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:20971520 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:05] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:31457280 (preload: true)
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:05] DEBUG  : Deleted chunk 1AbnRhxOOYCqp1pCRZCV6c3hPDg9DhJD8:10485760
[PLEXDRIVE-LINUX-ARM64] [2021-03-05 22:05] DEBUG  : Starting download 1Q9kIl8kQpxMmkVTQqPYP2wtm0ZIvXqxG:0 (preload: false)

**Comment by Nothing4You** [comment]
Plex's media scan will likely be looking at the files e.g. to determine screen resolution, runtime, etc, so that should be expected.

**Comment by dinjojo** [comment]
Thanks Nothing4You have been nothing more than helpful , all set now

**Comment by felixbuenemann** [comment]
I suggest these Plex Media Server Library Settings:

- Disable Scan my library automatically
- Enable Run a partial scan when changes are detected
- Enable Scan my library periodically (optional)
- Disable Empty trash automatically after every scan
- Generate video preview thumbnails: never
- Generate intro video markers: never
- Generate chapter thumbnails: never
- Analyze audio tracks for loudness: never
