### ISSUE TITLE
--drive-acknowledge-abuse Equivalent in Plexdrive?

### ISSUE THREAD

**Issue by JeramieG-IDG** [plexdrive/plexdrive#399]
is there a command line switch that allows files marked as spam or malware by google drive to still be downloaded in Plexdrive?  something similar to the RClone --drive-acknowledge-abuse switch?

the current command line is plexdrive mount -v 3 --chunk-check-threads=16 --chunk-load-threads=16 --chunk-load-ahead=16 --max-chunks=256 /home/user/mountedfolder/

and some files get 403 errors "cannotdownloadabusivefile"

thanks

**Comment by zenjabba** [comment]
Not currently
