### ISSUE TITLE
High Download, Low Upload..?

### ISSUE THREAD

**Issue by Skyfay** [plexdrive/plexdrive#403]
Before I used Plexdrive, I had media directly on the hard drives. Then of course I only had one upload. Now Plexdrive loads the data from Google and then loads them to the user. Yesterday 5 streams were running at the same time and I noticed that an extreme download came about.

![image](https://user-images.githubusercontent.com/76796007/141460078-24f5aa1c-2cb9-48ef-8ecc-2303a0c4dd48.png)
![image](https://user-images.githubusercontent.com/76796007/141460103-3d05df24-48fd-4dec-a03e-56d3db2467af.png)
![image](https://user-images.githubusercontent.com/76796007/141460124-517b10b6-0b98-428d-bf1a-5bd8d2c892af.png)

It may be important to say that I am using Emby and not Plex. Is there somehow the possibility to limit the download because I also noticed that the streaming and loading became slower.

**Comment by felixbuenemann** [comment]
* What parameters do you use to run plexdrive?
* What is the average bitrate of your streams?
* How many parallel streams are you expecting at maximum?

**Comment by Skyfay** [comment]
@felixbuenemann Thank you for your prompt reply.

> * What parameters do you use to run plexdrive?

./plexdrive-linux-amd64 mount -o allow_other -v 2 --refresh-interval=1m --root-node-id=xxxxxxxxx /mnt/plexdrive/

> * What is the average bitrate of your streams?

Different. Could be 3000 kbps but also up to 20'000 kbps. But i think the most Movies and Series are abount 5000-8000 kbps.

> * How many parallel streams are you expecting at maximum?

I think 8 streams. However, it could possibly be even more, depending on the situation.

**Comment by felixbuenemann** [comment]
You currently run with the default for `--max-chunks~ which is two, so only 2x 10MB chunks are kept in memory, so you are constantly re-downloading chunks, that were already requested and that causes excessive download.

Try with these settings:

* `--chunk-check-threads=16` request up to 16 chunks in parallel from cache
* `--chunk-load-threads=16` download up to 16 chunks in parallel from google drive
* `--chunk-load-ahead=3` download the next 3 chunks before they are requested, so you cache 4x10MB for each stream, that's enough for 4K high bitrate, for 1080p `--chunk-load-ahead=2` will probably be enough
* `--max-chunks=128` cache 128x10MB chunks in memory, if zoh have enough RAM you can use more, if you don't have enough RAM, use at least `chunk-load-threads * (chunk-load-ahead + 1)` which would be `--max-chunks=64`

These settings should easily handle 16 parallel streams. So if zou're low on RAM consider checke-thread/load-threads 8 and max-chunks=32 or even load-ahead=2 with max-chunks=24.

To calculate memory usage use something like `max-chunks * chunk-size * 2` with the current version of plexdrive and the default chunk-sie is 10MB.

**Comment by Skyfay** [comment]
Looks much better now. Thanks a lot!
