### ISSUE TITLE
Emby cannot write files

### ISSUE THREAD

**Issue by Skyfay** [plexdrive/plexdrive#404]
With Emby you can set that it creates nfo files for new media.
However, somehow he cannot create or fill files with plexdrive.

`./plexdrive-linux-amd64 mount -o allow_other -v 2 --refresh-interval=1m --root-node-id=11`

Do you have a solution for me?

**Comment by Nothing4You** [comment]
if you read the readme you will find this:

> Please note that plexdrive doesn't currently support writes (adding new files or modifications), it only supports reading existing files and deletion.

**Comment by adx74** [comment]
This is an old text I think, because you can write on it, add, edit, etc

**Comment by Nothing4You** [comment]
what makes you say that?
because it certainly doesn't work for me.

the only write actions working for me are creating folders (mkdir) and deleting files/folders (rm/rmdir).
trying to write files results in `Operation not permitted`

**Comment by adx74** [comment]
Yes I mean folders for creation (sorry), but for editing you can rename or move a file

**Comment by Nothing4You** [comment]
ah right, mv (renaming files and folders) should also work.
@Skyfay's request however explicitly mentioned creating files, which is not supported.

**Comment by felixbuenemann** [comment]
Yeah, plexdrive is pretty much read-only, so closing this.
